/** 
/* @file codify_definies.hpp
* @brief Defines for this project
*
* @section LICENSE
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR/AUTHORS BE LIABLE FOR ANY
* DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
* @author Alessandro Moro <alessandromoro.italy@gmail.com>
* @bug No known bugs.
* @version 0.1.0.0
*
*/

#ifndef STOREDATA_CODIFY_DEFINES_HPP__
#define STOREDATA_CODIFY_DEFINES_HPP__

#include "core/storedata_defines.hpp"

#if STOREDATADLL_USE_LIB == 1

#ifdef STOREDATACODIFYDLL
#define STOREDATA_CODIFY_EXPORT
#else
#define STOREDATA_CODIFY_EXPORT
#endif

#else // STOREDATADLL_USE_LIB != 1

// https://stackoverflow.com/questions/59718402/getting-around-declspecdllimport-in-windows-to-linux-project-conversion
#if defined(_WIN32) && !defined(STOREDATA_CODIFY_EXPORT)
#ifdef STOREDATACODIFYDLL
// Compiling a Windows DLL
#define STOREDATA_CODIFY_EXPORT __declspec(dllexport)
#else
// Using a Windows DLL
#define STOREDATA_CODIFY_EXPORT __declspec(dllimport)
#endif
// Windows or Linux static library, or Linux so
#else
#    define STOREDATA_CODIFY_EXPORT
#endif

#endif // STOREDATADLL_USE_LIB

#endif // STOREDATA_CODIFY_DEFINES_HPP__
